# Generated by Django 2.1.2 on 2018-11-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearthstone', '0003_auto_20181113_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='extension',
            field=models.TextField(default='Basic', max_length=60),
        ),
    ]
