# Generated by Django 2.1.2 on 2018-11-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearthstone', '0004_card_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='playerClass',
            field=models.TextField(default='NaN', max_length=50),
        ),
    ]
